Migrate to `hatch`
emscripten-forge/empack pull request #64
Opened 2023-04-03 08:24 UTC by jtpio

Aligning the packaging story with the other projects: https://blog.jupyter.org/packaging-for-jupyter-in-2022-c7be64c38926 (although `empack` is not strictly related to Jupyter).

One can use the `hatch version` command to bump version:

![image](https://user-images.githubusercontent.com/591645/229453395-772d81c5-ffd6-49ff-a33d-deae4cc5974b.png)

2023-04-03 11:57 UTC, jtpio commented
cc @martinRenou for review and for triggering the CI run

2023-04-06 12:00 UTC, jtpio commented
ping @martinRenou

I checked on my fork and CI seems to be passing: https://github.com/jtpio/empack/pull/1

2023-04-06 12:15 UTC, martinRenou requested changes
Thanks!

2023-04-06 12:15 UTC, martinRenou commented on pyproject.toml
> +    "pydantic",
pydantic is there twice, it was already the case before but since we're touching this file let's fix it

```suggestion
```

2023-04-07 09:12 UTC, martinRenou approved these changes
LGTM! Thanks

2023-04-07 09:15 UTC, merged